// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reddit_proto/reddit_comment.proto

/*
Package reddit_proto is a generated protocol buffer package.

It is generated from these files:
	reddit_proto/reddit_comment.proto

It has these top-level messages:
	Comment
*/
package reddit_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Comment struct {
	Author              *string `protobuf:"bytes,1,req,name=Author" json:"Author,omitempty"`
	Body                *string `protobuf:"bytes,2,req,name=Body" json:"Body,omitempty"`
	AuthorFlairCssClass *string `protobuf:"bytes,16,opt,name=AuthorFlairCssClass" json:"AuthorFlairCssClass,omitempty"`
	AuthorFlairText     *string `protobuf:"bytes,17,opt,name=AuthorFlairText" json:"AuthorFlairText,omitempty"`
	Controversiality    *int32  `protobuf:"varint,18,opt,name=Controversiality" json:"Controversiality,omitempty"`
	CreatedUTC          *int64  `protobuf:"varint,6,opt,name=CreatedUTC" json:"CreatedUTC,omitempty"`
	Edited              *string `protobuf:"bytes,7,opt,name=Edited" json:"Edited,omitempty"`
	Gilded              *int32  `protobuf:"varint,19,opt,name=Gilded" json:"Gilded,omitempty"`
	Id                  *string `protobuf:"bytes,9,req,name=Id" json:"Id,omitempty"`
	LinkId              *string `protobuf:"bytes,22,opt,name=LinkId" json:"LinkId,omitempty"`
	ParentId            *string `protobuf:"bytes,20,opt,name=ParentId" json:"ParentId,omitempty"`
	RetrievedOn         *int64  `protobuf:"varint,23,opt,name=RetrievedOn" json:"RetrievedOn,omitempty"`
	Score               *int32  `protobuf:"varint,13,req,name=Score" json:"Score,omitempty"`
	Subreddit           *string `protobuf:"bytes,14,req,name=Subreddit" json:"Subreddit,omitempty"`
	SubredditId         *string `protobuf:"bytes,15,req,name=SubredditId" json:"SubredditId,omitempty"`
	Ups                 *int32  `protobuf:"varint,21,opt,name=Ups" json:"Ups,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Comment) GetAuthor() string {
	if m != nil && m.Author != nil {
		return *m.Author
	}
	return ""
}

func (m *Comment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Comment) GetAuthorFlairCssClass() string {
	if m != nil && m.AuthorFlairCssClass != nil {
		return *m.AuthorFlairCssClass
	}
	return ""
}

func (m *Comment) GetAuthorFlairText() string {
	if m != nil && m.AuthorFlairText != nil {
		return *m.AuthorFlairText
	}
	return ""
}

func (m *Comment) GetControversiality() int32 {
	if m != nil && m.Controversiality != nil {
		return *m.Controversiality
	}
	return 0
}

func (m *Comment) GetCreatedUTC() int64 {
	if m != nil && m.CreatedUTC != nil {
		return *m.CreatedUTC
	}
	return 0
}

func (m *Comment) GetEdited() string {
	if m != nil && m.Edited != nil {
		return *m.Edited
	}
	return ""
}

func (m *Comment) GetGilded() int32 {
	if m != nil && m.Gilded != nil {
		return *m.Gilded
	}
	return 0
}

func (m *Comment) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Comment) GetLinkId() string {
	if m != nil && m.LinkId != nil {
		return *m.LinkId
	}
	return ""
}

func (m *Comment) GetParentId() string {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return ""
}

func (m *Comment) GetRetrievedOn() int64 {
	if m != nil && m.RetrievedOn != nil {
		return *m.RetrievedOn
	}
	return 0
}

func (m *Comment) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Comment) GetSubreddit() string {
	if m != nil && m.Subreddit != nil {
		return *m.Subreddit
	}
	return ""
}

func (m *Comment) GetSubredditId() string {
	if m != nil && m.SubredditId != nil {
		return *m.SubredditId
	}
	return ""
}

func (m *Comment) GetUps() int32 {
	if m != nil && m.Ups != nil {
		return *m.Ups
	}
	return 0
}

func init() {
	proto.RegisterType((*Comment)(nil), "reddit_proto.Comment")
}

func init() { proto.RegisterFile("reddit_proto/reddit_comment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x6a, 0x52, 0x33, 0x69, 0xd3, 0x74, 0xa3, 0x76, 0xc0, 0x4b, 0xf4, 0x94, 0x93,
	0x3e, 0x83, 0x2e, 0x2a, 0x01, 0x41, 0xb1, 0xed, 0x59, 0x62, 0x67, 0xc0, 0xc5, 0x34, 0x5b, 0x76,
	0xb7, 0xc5, 0xbe, 0x96, 0x4f, 0x28, 0xdd, 0x88, 0xf4, 0x38, 0xdf, 0x37, 0xff, 0xee, 0xcf, 0xc0,
	0x95, 0x61, 0x22, 0xe5, 0xde, 0x37, 0x46, 0x3b, 0x7d, 0xfb, 0x37, 0xac, 0xf4, 0x7a, 0xcd, 0x9d,
	0xbb, 0xf1, 0x50, 0x8c, 0x8e, 0x57, 0xae, 0x7f, 0x42, 0x18, 0xca, 0xde, 0x8b, 0x0c, 0xe2, 0xbb,
	0xad, 0xfb, 0xd4, 0x06, 0x83, 0x32, 0xac, 0x12, 0x31, 0x82, 0x93, 0x7b, 0x4d, 0x7b, 0x0c, 0xfd,
	0x74, 0x09, 0x45, 0x6f, 0x1f, 0xdb, 0x46, 0x19, 0x69, 0xad, 0x6c, 0x1b, 0x6b, 0x31, 0x2f, 0x83,
	0x2a, 0x11, 0x33, 0x98, 0x1c, 0xc9, 0x05, 0x7f, 0x3b, 0x9c, 0x7a, 0x81, 0x90, 0x4b, 0xdd, 0x39,
	0xa3, 0x77, 0x6c, 0xac, 0x6a, 0x5a, 0xe5, 0xf6, 0x28, 0xca, 0xa0, 0x8a, 0x84, 0x00, 0x90, 0x86,
	0x1b, 0xc7, 0xb4, 0x5c, 0x48, 0x8c, 0xcb, 0xa0, 0x1a, 0x1c, 0x1a, 0x3c, 0x90, 0x72, 0x4c, 0x38,
	0xf4, 0xe9, 0x0c, 0xe2, 0x27, 0xd5, 0x12, 0x13, 0x16, 0x3e, 0x03, 0x10, 0xd6, 0x84, 0x89, 0xef,
	0x93, 0x41, 0xfc, 0xac, 0xba, 0xaf, 0x9a, 0xf0, 0xc2, 0xef, 0xe6, 0x70, 0xfa, 0xda, 0x18, 0xee,
	0x5c, 0x4d, 0x78, 0xe6, 0x49, 0x01, 0xe9, 0x1b, 0x3b, 0xa3, 0x78, 0xc7, 0xf4, 0xd2, 0xe1, 0xcc,
	0x7f, 0x31, 0x86, 0x68, 0xbe, 0xd2, 0x86, 0x71, 0x5c, 0x86, 0x55, 0x24, 0xa6, 0x90, 0xcc, 0xb7,
	0x1f, 0xfd, 0x49, 0x30, 0xf3, 0x0f, 0x17, 0x90, 0xfe, 0xa3, 0x9a, 0x70, 0xe2, 0x61, 0x0a, 0x83,
	0xe5, 0xc6, 0xe2, 0xf9, 0xa1, 0xc6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xe3, 0x38, 0xfc,
	0x66, 0x01, 0x00, 0x00,
}
